language: node_js

node_js:
  - "11.13.0"

branches:
  only:
  - master
  - version-0.1.1

install:
  - yarn install

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage